"""Phase 3: telemetry hypertable, aggregates, state transitions, health history.

Autogenerated from models.py, then reviewed by hand: the ``measurements``
table becomes a TimescaleDB hypertable and gains minute/hour/day continuous
aggregates (min/max/avg/count/stddev per entity/measurement/unit). Continuous
aggregates cannot be created inside a transaction, so those statements run in
an autocommit block. The aggregate views live outside the ORM metadata; the
model/migration parity test only compares tables and is unaffected.

Revision ID: dbfc40d327c0
Revises: a526ee7fcfdb
Create Date: 2026-07-16 11:08:52.733922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dbfc40d327c0'
down_revision: Union[str, None] = 'a526ee7fcfdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('measurement_name', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value_double', sa.Double(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_measurements_confidence_range')),
    sa.PrimaryKeyConstraint('time', 'entity_id', 'measurement_name', 'source_id', name=op.f('pk_measurements'))
    )
    op.create_index('ix_measurements_entity_name_time', 'measurements', ['entity_id', 'measurement_name', 'time'], unique=False)
    op.create_index('ix_measurements_source_time', 'measurements', ['source_id', 'time'], unique=False)
    op.create_table('state_transitions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('from_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('to_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_transitions'))
    )
    op.create_index('ix_state_transitions_entity_occurred', 'state_transitions', ['entity_id', 'occurred_at'], unique=False)
    op.create_index('ix_state_transitions_property_occurred', 'state_transitions', ['property_name', 'occurred_at'], unique=False)
    op.create_table('source_health_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('health_status', sa.String(length=30), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health_status IN ('healthy', 'degraded', 'stale', 'offline', 'misconfigured', 'unauthorized', 'unknown')", name=op.f('ck_source_health_history_health_status_valid')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_source_health_history_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_health_history'))
    )
    op.create_index('ix_source_health_history_source_changed', 'source_health_history', ['source_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###

    op.execute(
        "SELECT create_hypertable('measurements', 'time', "
        "chunk_time_interval => INTERVAL '7 days', "
        "create_default_indexes => FALSE)"  # model-declared indexes suffice
    )

    with op.get_context().autocommit_block():
        for view, bucket in (
            ("measurements_1m", "1 minute"),
            ("measurements_1h", "1 hour"),
            ("measurements_1d", "1 day"),
        ):
            op.execute(
                f"CREATE MATERIALIZED VIEW {view} "
                "WITH (timescaledb.continuous) AS "
                f"SELECT time_bucket(INTERVAL '{bucket}', time) AS bucket, "
                "entity_id, measurement_name, unit, "
                "min(value_double) AS value_min, "
                "max(value_double) AS value_max, "
                "avg(value_double) AS value_avg, "
                "count(*) AS sample_count, "
                "stddev(value_double) AS value_stddev "
                "FROM measurements "
                "GROUP BY bucket, entity_id, measurement_name, unit "
                "WITH NO DATA"
            )
    # Refresh policies keep the aggregates current in the background; tests
    # and backfills may also call refresh_continuous_aggregate explicitly.
    op.execute(
        "SELECT add_continuous_aggregate_policy('measurements_1m', "
        "start_offset => INTERVAL '2 hours', end_offset => INTERVAL '1 minute', "
        "schedule_interval => INTERVAL '1 minute')"
    )
    op.execute(
        "SELECT add_continuous_aggregate_policy('measurements_1h', "
        "start_offset => INTERVAL '2 days', end_offset => INTERVAL '1 hour', "
        "schedule_interval => INTERVAL '30 minutes')"
    )
    op.execute(
        "SELECT add_continuous_aggregate_policy('measurements_1d', "
        "start_offset => INTERVAL '7 days', end_offset => INTERVAL '1 day', "
        "schedule_interval => INTERVAL '6 hours')"
    )


def downgrade() -> None:
    op.execute("SELECT remove_continuous_aggregate_policy('measurements_1d', if_exists => true)")
    op.execute("SELECT remove_continuous_aggregate_policy('measurements_1h', if_exists => true)")
    op.execute("SELECT remove_continuous_aggregate_policy('measurements_1m', if_exists => true)")
    with op.get_context().autocommit_block():
        op.execute("DROP MATERIALIZED VIEW IF EXISTS measurements_1d")
        op.execute("DROP MATERIALIZED VIEW IF EXISTS measurements_1h")
        op.execute("DROP MATERIALIZED VIEW IF EXISTS measurements_1m")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_health_history_source_changed', table_name='source_health_history')
    op.drop_table('source_health_history')
    op.drop_index('ix_state_transitions_property_occurred', table_name='state_transitions')
    op.drop_index('ix_state_transitions_entity_occurred', table_name='state_transitions')
    op.drop_table('state_transitions')
    op.drop_index('ix_measurements_source_time', table_name='measurements')
    op.drop_index('ix_measurements_entity_name_time', table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
