"""phase 8 artifacts

Revision ID: 3337c328523b
Revises: e7c11f9a4b2d
Create Date: 2026-07-16 20:54:52.496566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3337c328523b'
down_revision: Union[str, None] = 'e7c11f9a4b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('retention_class', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('relative_path', name=op.f('uq_artifacts_relative_path'))
    )
    op.create_index('ix_artifacts_created_at', 'artifacts', ['created_at'], unique=False)
    op.create_index('ix_artifacts_kind', 'artifacts', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifacts_kind', table_name='artifacts')
    op.drop_index('ix_artifacts_created_at', table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
