"""phase 7 action requests

Revision ID: 4d268f4eae02
Revises: abc5ba9b578d
Create Date: 2026-07-16 15:23:44.490501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4d268f4eae02'
down_revision: Union[str, None] = 'abc5ba9b578d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_requests',
    sa.Column('action_request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('target_entity_id', sa.String(length=200), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('parameters_hash', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='requested', nullable=False),
    sa.Column('command_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('confirmation_token', sa.String(length=64), nullable=True),
    sa.Column('confirmation_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timeout_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('requested', 'rejected', 'awaiting_confirmation', 'approved', 'dispatched', 'acknowledged', 'completed', 'failed', 'timed_out', 'cancelled')", name=op.f('ck_action_requests_status_valid')),
    sa.PrimaryKeyConstraint('action_request_id', name=op.f('pk_action_requests')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_action_requests_idempotency_key'))
    )
    op.create_index('ix_action_requests_action_created', 'action_requests', ['action_name', 'created_at'], unique=False)
    op.create_index('ix_action_requests_command_id', 'action_requests', ['command_id'], unique=False)
    op.create_index('ix_action_requests_status', 'action_requests', ['status'], unique=False)
    op.create_table('action_transitions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('action_request_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_request_id'], ['action_requests.action_request_id'], name=op.f('fk_action_transitions_action_request_id_action_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_transitions'))
    )
    op.create_index('ix_action_transitions_request', 'action_transitions', ['action_request_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_action_transitions_request', table_name='action_transitions')
    op.drop_table('action_transitions')
    op.drop_index('ix_action_requests_status', table_name='action_requests')
    op.drop_index('ix_action_requests_command_id', table_name='action_requests')
    op.drop_index('ix_action_requests_action_created', table_name='action_requests')
    op.drop_table('action_requests')
    # ### end Alembic commands ###
