"""phase 4 notification deliveries

Revision ID: 7bf1cd5508d3
Revises: dbfc40d327c0
Create Date: 2026-07-16 11:33:33.402544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7bf1cd5508d3'
down_revision: Union[str, None] = 'dbfc40d327c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('attention_item_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('recipient_or_endpoint', sa.String(length=300), nullable=True),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=300), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('delivered', 'failed')", name=op.f('ck_notification_deliveries_status_valid')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('fk_notification_deliveries_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attention_item_id'], ['attention_items.attention_item_id'], name=op.f('fk_notification_deliveries_attention_item_id_attention_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index('ix_notification_deliveries_alert_id', 'notification_deliveries', ['alert_id'], unique=False)
    op.create_index('ix_notification_deliveries_attempted_at', 'notification_deliveries', ['attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_deliveries_attempted_at', table_name='notification_deliveries')
    op.drop_index('ix_notification_deliveries_alert_id', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
