"""Phase 1 foundation: extensions, registry, events, state, alerts, outbox.

Autogenerated from talos/awareness/db/models.py against a clean database,
then reviewed by hand (extensions + schema_registry seed added). The
model/migration parity is enforced by tests/test_awareness_migrations.py.

Revision ID: a526ee7fcfdb
Revises:
Create Date: 2026-07-15 20:43:39.430850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a526ee7fcfdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required extensions. The timescale/timescaledb-ha image ships both;
    # scratch/test databases created on the same server get them here.
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('dead_letter_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=False),
    sa.Column('topic_or_endpoint', sa.String(length=512), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('source_hint', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_events'))
    )
    op.create_index('ix_dead_letter_events_reason', 'dead_letter_events', ['reason'], unique=False)
    op.create_index('ix_dead_letter_events_received_at', 'dead_letter_events', ['received_at'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), server_default='room', nullable=False),
    sa.Column('parent_location_id', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.location_id'], name=op.f('fk_locations_parent_location_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('location_id', name=op.f('pk_locations'))
    )
    op.create_table('outbox',
    sa.Column('outbox_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=True),
    sa.Column('aggregate_id', sa.String(length=300), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('available_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=200), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'dead_letter')", name=op.f('ck_outbox_status_valid')),
    sa.PrimaryKeyConstraint('outbox_id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbox_idempotency_key'))
    )
    op.create_index('ix_outbox_status_available', 'outbox', ['status', 'available_at'], unique=False)
    op.create_index('ix_outbox_status_next_attempt', 'outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_outbox_work_type', 'outbox', ['work_type'], unique=False)
    op.create_table('schema_registry',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_registry')),
    sa.UniqueConstraint('kind', 'name', 'version', name='uq_schema_registry_kind_name_version')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('person', 'plant', 'device', 'controller', 'sensor', 'actuator', 'service', 'automation', 'agent', 'notification_endpoint')", name=op.f('ck_entities_entity_type_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name=op.f('fk_entities_location_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entities'))
    )
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_location_id', 'entities', ['location_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('deduplication_key', sa.String(length=300), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notification_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('debug', 'info', 'notice', 'warning', 'critical')", name=op.f('ck_alerts_severity_valid')),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'suppressed', 'resolved', 'expired')", name=op.f('ck_alerts_status_valid')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_alerts_entity_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_entity_id', 'alerts', ['entity_id'], unique=False)
    op.create_index('ix_alerts_opened_at', 'alerts', ['opened_at'], unique=False)
    op.create_index('ix_alerts_status_severity', 'alerts', ['status', 'severity'], unique=False)
    op.create_index('uq_alerts_active_dedup', 'alerts', ['deduplication_key'], unique=True, postgresql_where=sa.text("status IN ('open', 'acknowledged') AND deduplication_key IS NOT NULL"))
    op.create_table('entity_relationships',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=200), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('object_entity_id', sa.String(length=200), nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.entity_id'], name=op.f('fk_entity_relationships_object_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.entity_id'], name=op.f('fk_entity_relationships_subject_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationships'))
    )
    op.create_index('ix_entity_relationships_object', 'entity_relationships', ['object_entity_id', 'relation'], unique=False)
    op.create_index('ix_entity_relationships_subject', 'entity_relationships', ['subject_entity_id', 'relation'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('transport', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.String(length=200), nullable=True),
    sa.Column('firmware_version', sa.String(length=100), nullable=True),
    sa.Column('software_version', sa.String(length=100), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('expected_update_interval_seconds', sa.Float(), nullable=True),
    sa.Column('stale_after_seconds', sa.Float(), nullable=True),
    sa.Column('offline_after_seconds', sa.Float(), nullable=True),
    sa.Column('clock_quality', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('last_observed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_received_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sequence', sa.BigInteger(), nullable=True),
    sa.Column('last_boot_id', sa.String(length=200), nullable=True),
    sa.Column('health_status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('authentication_identity', sa.String(length=200), nullable=True),
    sa.Column('allowed_topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("clock_quality IN ('unknown', 'unsynchronized', 'device_local', 'device_synced', 'gateway_stamped', 'server_received')", name=op.f('ck_sources_clock_quality_valid')),
    sa.CheckConstraint("health_status IN ('healthy', 'degraded', 'stale', 'offline', 'misconfigured', 'unauthorized', 'unknown')", name=op.f('ck_sources_health_status_valid')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_sources_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name=op.f('fk_sources_location_id_locations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_sources'))
    )
    op.create_index('ix_sources_entity_id', 'sources', ['entity_id'], unique=False)
    op.create_index('ix_sources_health_status', 'sources', ['health_status'], unique=False)
    op.create_table('attention_items',
    sa.Column('attention_item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('available_after', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('interruptibility', sa.String(length=30), server_default='next_interaction', nullable=False),
    sa.Column('preferred_channel', sa.String(length=100), nullable=True),
    sa.Column('cooldown_key', sa.String(length=300), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('conversation_relevance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("delivery_status IN ('pending', 'delivering', 'delivered', 'failed', 'expired', 'cancelled')", name=op.f('ck_attention_items_delivery_status_valid')),
    sa.CheckConstraint("interruptibility IN ('immediate', 'interrupt_when_safe', 'next_interaction', 'passive')", name=op.f('ck_attention_items_interruptibility_valid')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('fk_attention_items_alert_id_alerts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('attention_item_id', name=op.f('pk_attention_items'))
    )
    op.create_index('ix_attention_items_alert_id', 'attention_items', ['alert_id'], unique=False)
    op.create_index('ix_attention_items_cooldown_key', 'attention_items', ['cooldown_key'], unique=False)
    op.create_index('ix_attention_items_delivery', 'attention_items', ['delivery_status', 'available_after'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.String(length=200), nullable=True),
    sa.Column('observed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=True),
    sa.Column('source_boot_id', sa.String(length=200), nullable=True),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.Column('causation_id', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('retention_class', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('debug', 'info', 'notice', 'warning', 'critical')", name=op.f('ck_events_severity_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_events_confidence_range')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_events_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_causation_id', 'events', ['causation_id'], unique=False)
    op.create_index('ix_events_correlation_id', 'events', ['correlation_id'], unique=False)
    op.create_index('ix_events_entity_received', 'events', ['entity_id', 'received_at'], unique=False)
    op.create_index('ix_events_observed_at', 'events', ['observed_at'], unique=False)
    op.create_index('ix_events_received_at', 'events', ['received_at'], unique=False)
    op.create_index('ix_events_severity_received', 'events', ['severity', 'received_at'], unique=False)
    op.create_index('ix_events_source_received', 'events', ['source_id', 'received_at'], unique=False)
    op.create_index('ix_events_type_received', 'events', ['event_type', 'received_at'], unique=False)
    op.create_index('uq_events_source_boot_sequence', 'events', ['source_id', 'source_boot_id', 'sequence'], unique=True, postgresql_where=sa.text('sequence IS NOT NULL AND source_boot_id IS NOT NULL'))
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), server_default='evidence', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('fk_alert_events_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name=op.f('fk_alert_events_event_id_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events')),
    sa.UniqueConstraint('alert_id', 'event_id', name='uq_alert_events_alert_event')
    )
    op.create_index('ix_alert_events_alert_id', 'alert_events', ['alert_id'], unique=False)
    op.create_index('ix_alert_events_event_id', 'alert_events', ['event_id'], unique=False)
    op.create_table('current_state',
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('state_status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('authority_rank', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("state_status IN ('current', 'stale', 'unknown', 'conflicting', 'offline', 'inferred', 'scheduled')", name=op.f('ck_current_state_state_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_current_state_confidence_range')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], name=op.f('fk_current_state_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.event_id'], name=op.f('fk_current_state_source_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], name=op.f('fk_current_state_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entity_id', 'property_name', name=op.f('pk_current_state'))
    )
    op.create_index('ix_current_state_expires_at', 'current_state', ['expires_at'], unique=False)
    op.create_index('ix_current_state_source_id', 'current_state', ['source_id'], unique=False)
    op.create_index('ix_current_state_status', 'current_state', ['state_status'], unique=False)

    # Record the canonical envelope schema version this database understands.
    op.execute(
        "INSERT INTO schema_registry (kind, name, version) "
        "VALUES ('event_envelope', 'core', 1)"
    )


def downgrade() -> None:
    # Extensions are intentionally left installed on downgrade.
    op.drop_index('ix_current_state_status', table_name='current_state')
    op.drop_index('ix_current_state_source_id', table_name='current_state')
    op.drop_index('ix_current_state_expires_at', table_name='current_state')
    op.drop_table('current_state')
    op.drop_index('ix_alert_events_event_id', table_name='alert_events')
    op.drop_index('ix_alert_events_alert_id', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('uq_events_source_boot_sequence', table_name='events', postgresql_where=sa.text('sequence IS NOT NULL AND source_boot_id IS NOT NULL'))
    op.drop_index('ix_events_type_received', table_name='events')
    op.drop_index('ix_events_source_received', table_name='events')
    op.drop_index('ix_events_severity_received', table_name='events')
    op.drop_index('ix_events_received_at', table_name='events')
    op.drop_index('ix_events_observed_at', table_name='events')
    op.drop_index('ix_events_entity_received', table_name='events')
    op.drop_index('ix_events_correlation_id', table_name='events')
    op.drop_index('ix_events_causation_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_attention_items_delivery', table_name='attention_items')
    op.drop_index('ix_attention_items_cooldown_key', table_name='attention_items')
    op.drop_index('ix_attention_items_alert_id', table_name='attention_items')
    op.drop_table('attention_items')
    op.drop_index('ix_sources_health_status', table_name='sources')
    op.drop_index('ix_sources_entity_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_entity_relationships_subject', table_name='entity_relationships')
    op.drop_index('ix_entity_relationships_object', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index('uq_alerts_active_dedup', table_name='alerts', postgresql_where=sa.text("status IN ('open', 'acknowledged') AND deduplication_key IS NOT NULL"))
    op.drop_index('ix_alerts_status_severity', table_name='alerts')
    op.drop_index('ix_alerts_opened_at', table_name='alerts')
    op.drop_index('ix_alerts_entity_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_entities_location_id', table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_table('entities')
    op.drop_table('schema_registry')
    op.drop_index('ix_outbox_work_type', table_name='outbox')
    op.drop_index('ix_outbox_status_next_attempt', table_name='outbox')
    op.drop_index('ix_outbox_status_available', table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('locations')
    op.drop_index('ix_dead_letter_events_received_at', table_name='dead_letter_events')
    op.drop_index('ix_dead_letter_events_reason', table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    # ### end Alembic commands ###
