"""phase 6 long-term memory

Revision ID: abc5ba9b578d
Revises: 7bf1cd5508d3
Create Date: 2026-07-16 15:12:04.904987

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'abc5ba9b578d'
down_revision: Union[str, None] = '7bf1cd5508d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('memory_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('importance', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('scope', sa.String(length=200), server_default='general', nullable=False),
    sa.Column('sensitivity', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('valid_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('learned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('supersedes_memory_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='candidate', nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('embedded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("memory_type IN ('semantic', 'episodic')", name=op.f('ck_memories_memory_type_valid')),
    sa.CheckConstraint("sensitivity IN ('normal', 'personal', 'sensitive', 'restricted')", name=op.f('ck_memories_sensitivity_valid')),
    sa.CheckConstraint("status IN ('candidate', 'accepted', 'rejected', 'active', 'superseded', 'expired', 'deleted')", name=op.f('ck_memories_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_memories_confidence_range')),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name=op.f('ck_memories_importance_range')),
    sa.ForeignKeyConstraint(['supersedes_memory_id'], ['memories.memory_id'], name=op.f('fk_memories_supersedes_memory_id_memories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('memory_id', name=op.f('pk_memories'))
    )
    op.create_index('ix_memories_learned_at', 'memories', ['learned_at'], unique=False)
    op.create_index('ix_memories_scope', 'memories', ['scope'], unique=False)
    op.create_index('ix_memories_statement_fts', 'memories', [sa.literal_column("to_tsvector('english', statement)")], unique=False, postgresql_using='gin')
    op.create_index('ix_memories_status_type', 'memories', ['status', 'memory_type'], unique=False)
    op.create_index('uq_memories_live_content_hash', 'memories', ['content_hash'], unique=True, postgresql_where=sa.text("status IN ('candidate', 'accepted', 'active')"))
    op.create_table('memory_embeddings',
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.memory_id'], name=op.f('fk_memory_embeddings_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('memory_id', name=op.f('pk_memory_embeddings'))
    )
    op.create_index('ix_memory_embeddings_vector', 'memory_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('memory_provenance',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=300), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('event', 'alert', 'message', 'conversation', 'source', 'user_confirmation', 'extraction_job', 'model')", name=op.f('ck_memory_provenance_kind_valid')),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.memory_id'], name=op.f('fk_memory_provenance_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_provenance'))
    )
    op.create_index('ix_memory_provenance_kind_ref', 'memory_provenance', ['kind', 'reference'], unique=False)
    op.create_index('ix_memory_provenance_memory_id', 'memory_provenance', ['memory_id'], unique=False)
    op.create_table('memory_relationships',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('from_memory_id', sa.UUID(), nullable=False),
    sa.Column('to_memory_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relation IN ('supersedes', 'conflicts_with', 'duplicates', 'derived_from')", name=op.f('ck_memory_relationships_relation_valid')),
    sa.ForeignKeyConstraint(['from_memory_id'], ['memories.memory_id'], name=op.f('fk_memory_relationships_from_memory_id_memories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_memory_id'], ['memories.memory_id'], name=op.f('fk_memory_relationships_to_memory_id_memories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_relationships')),
    sa.UniqueConstraint('from_memory_id', 'to_memory_id', 'relation', name='uq_memory_relationships_edge')
    )
    op.create_index('ix_memory_relationships_to', 'memory_relationships', ['to_memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_relationships_to', table_name='memory_relationships')
    op.drop_table('memory_relationships')
    op.drop_index('ix_memory_provenance_memory_id', table_name='memory_provenance')
    op.drop_index('ix_memory_provenance_kind_ref', table_name='memory_provenance')
    op.drop_table('memory_provenance')
    op.drop_index('ix_memory_embeddings_vector', table_name='memory_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('memory_embeddings')
    op.drop_index('uq_memories_live_content_hash', table_name='memories', postgresql_where=sa.text("status IN ('candidate', 'accepted', 'active')"))
    op.drop_index('ix_memories_status_type', table_name='memories')
    op.drop_index('ix_memories_statement_fts', table_name='memories', postgresql_using='gin')
    op.drop_index('ix_memories_scope', table_name='memories')
    op.drop_index('ix_memories_learned_at', table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
