"""reminders (due-time scheduled attention)

Revision ID: b8f2a1c7d3e9
Revises: 3337c328523b
Create Date: 2026-07-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b8f2a1c7d3e9'
down_revision: Union[str, None] = '3337c328523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('reminder_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('due_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fired_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attention_item_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=300), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'fired', 'cancelled', 'expired')", name=op.f('ck_reminders_status_valid')),
    sa.ForeignKeyConstraint(['attention_item_id'], ['attention_items.attention_item_id'], name=op.f('fk_reminders_attention_item_id_attention_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('reminder_id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_reminders_idempotency_key'))
    )
    op.create_index('ix_reminders_status_due_at', 'reminders', ['status', 'due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_status_due_at', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
